[phases.setup]
packages = ["nodejs_21", "yarn-1_x", "openssl", "promtail"]

[phases.install]
command = "yarn install --frozen-lockfile"

[phases.build]
command = "yarn run build"
files = ["promtail.yaml"]

[phases.start]
command = "yarn run start && promtail -config.file=promtail.yaml"