[setup]
packages = ["nodejs_21", "yarn-1_x", "openssl", "promtail"]

[install]
command = "yarn install --frozen-lockfile"

[build]
command = "yarn run build"
files = ["promtail.yaml"]

[start]
command = "yarn run start && promtail -config.file=promtail.yaml"